### ISSUE TITLE
Pode kolliderer med “graft”

### ISSUE THREAD

**Issue by thorehusfeldt** [thorehusfeldt/git-paa-dansk#4]
Ulykkeligt nok findes der i (efterhånden ganske gammel) engelsk gitterminologi allerede en brug av podning. Her bruges begrebet “graft” til at betegne flytning af en udviklingsgren mellen repositorier, og sågar mellem versionshåndteringssystemer. (Min forståelse er, at denne form for omstrukturering af repositoriet er erstatted med “git replace” siden version 1.6.5.) Denne flytning mellem træer er rimeligvis en bedre anvendelse af begrebet podning, som jo ganske rigtigt først og fremmest flytter en gren fra et træ til et andet.

Således er der altså mindst tre ting i vejen med “at pode” for “rebase”. For det første undviger man den direkte oversættelse (som skulle være genbasere eller rebasere eller noget lignende.) For det andet introducerer man billedsprog som er subtilt misvisende. For det trejde kolliderer man med etableret (omend forældet) engelsk gitterminologi.

**Comment by tmog** [comment]
Jeg er enig i ovenstående, særligt at det er problematisk når billedsproget er en smule misvisende. 
Et muligt alternativ er **genhuse** - som efter min vurdering giver et rigtig godt billede. Det er vel også netop den samme metafor som benyttes på engelsk.

**Comment by thorehusfeldt** [comment]
Jeg kan godt lide genhuse, men efter lidt detektivarbejde så bruges _rebasere_ både i tandlæge- og finansverdenen allerede præcis i den betydning, vi her efterlyser. Eftersom _rebasere_ ligger besnærende tæt på det engelske fagudtryk, finder jeg det bedst at bare anvende dette.
