### ISSUE TITLE
Forslag: Forke burde være at Gafle

### ISSUE THREAD

**Issue by pKorsholm** [thorehusfeldt/git-paa-dansk#7]

**Comment by thorehusfeldt** [comment]
Det virker umiddelbart overbevisende. Ordbog over det danske sprog har, under **gafle**:

2) Skriftsprog eller litterært påvirket talesprog refl.: _dele sig i to_ ell. _flere grene_; gaffeldele sig. en uanselig Vei . . gaflede sig i et Par Grene, der atter delte sig. Gjel.​T.261. Træerne staar som forgjorte med svulmende trinde Lemmer, gafler sig, som Væsener staaende paa Hovedet med Benene lige i Vejret, gaflede Træer allevegne. JVJens.​CT.136. (bjergv.:) En Gang . . deler sig i flere mindre Gange (gafler sig). Sal.​VII.482.

**Comment by thorehusfeldt** [comment]
Tilføjet i b7048f0a51cbdff89a383444f812c893fba80281
